// Codepackr Astro - Dedicated Legal Disclaimer Page
import { useLang } from "@/lib/lang";
import { useNav } from "@/lib/nav";
import { t } from "@/lib/astro/i18n";
import { ShieldAlert, ArrowLeft, CheckCircle2, AlertTriangle, FileText, Scale } from "lucide-react";

export function DisclaimerPage() {
  const { lang } = useLang();
  const { go } = useNav();

  const isTa = lang === "ta";

  return (
    <main className="mx-auto max-w-4xl px-4 py-8 sm:px-6 sm:py-12">
      <div className="mb-6 flex items-center justify-between">
        <button
          type="button"
          onClick={() => go("jathagam")}
          className="inline-flex items-center gap-1.5 text-xs sm:text-sm font-medium text-accent hover:underline"
        >
          <ArrowLeft className="size-4" />
          <span>{isTa ? "முகப்புக்குத் திரும்பு" : "Back to Home"}</span>
        </button>
        <span className="inline-flex items-center gap-1 rounded-full bg-accent/10 px-3 py-1 text-xs font-semibold text-accent border border-accent/20">
          <Scale className="size-3.5" />
          <span>{isTa ? "சட்டப்பூர்வ ஆவணம்" : "Legal Document"}</span>
        </span>
      </div>

      <article className="rounded-2xl border border-border/80 bg-surface p-6 sm:p-10 shadow-card">
        {/* Header */}
        <header className="border-b border-border/80 pb-6 text-center sm:text-left">
          <div className="inline-flex size-12 items-center justify-center rounded-xl bg-accent/10 text-accent mb-3">
            <ShieldAlert className="size-6" />
          </div>
          <h1 className="font-display text-2xl sm:text-3xl text-ink font-bold">
            {isTa ? "சட்டப்பூர்வ பொறுப்புத் துறப்பு" : "Legal Disclaimer & Terms of Use"}
          </h1>
          <p className="mt-2 text-sm text-muted">
            {isTa
              ? "astro.codepackr.com இணையதளம் மற்றும் PDF அறிக்கைகளுக்கான அதிகாரப்பூர்வ பொறுப்புத் துறப்பு."
              : "Official legal disclaimer for astro.codepackr.com and all downloadable / printable PDF reports."}
          </p>
        </header>

        {/* Primary Mandate Box */}
        <section className="mt-6 rounded-xl border-2 border-accent/30 bg-accent/5 p-5 text-sm leading-relaxed text-ink">
          <div className="flex items-start gap-3">
            <AlertTriangle className="size-5 shrink-0 text-accent mt-0.5" />
            <div>
              <h2 className="font-bold text-accent text-base mb-1">
                {isTa ? "சட்டப்பூர்வ பொறுப்புத் துறப்பு அறிக்கை" : "Statutory Disclaimer Statement"}
              </h2>
              <p className="font-medium text-fg">
                {isTa
                  ? "பொறுப்புத் துறப்பு: இவ்வறிக்கை பயனரால் உள்ளிடப்பட்ட பிறந்த விபரங்களின் அடிப்படையில் கணினி மூலம் தானாகக் கணிக்கப்பட்டதாகும். இது வழிகாட்டுதலுக்காக மட்டுமே வழங்கப்படுகிறது. திருமணம், தொழில், நிதி மற்றும் மருத்துவம் சார்ந்த முக்கிய முடிவுகளுக்கு அனுபவமிக்க பாரம்பரிய ஜோதிடரிடம் சரிபார்த்துக் கொள்ளவும். இவ்வறிக்கையின் அடிப்படையில் எடுக்கப்படும் முடிவுகளுக்கு மென்பொருள் நிர்வாகமோ உருவாக்குநர்களோ எவ்வித சட்டரீதியான பொறுப்பும் ஏற்க மாட்டார்கள்."
                  : "Disclaimer: This report is automatically generated by computer software based on user-provided birth details. It is intended solely for guidance and informational purposes. Please consult an experienced astrologer before making significant matrimonial, financial, or personal decisions. The developers and publishers assume no legal liability for any actions taken based on this report."}
              </p>
            </div>
          </div>
        </section>

        {/* Detailed Sections */}
        <div className="mt-8 space-y-6 text-sm text-fg leading-relaxed">
          {/* Section 1 */}
          <div className="rounded-xl border border-border/70 bg-elevated/30 p-5">
            <h3 className="font-semibold text-ink text-base flex items-center gap-2">
              <CheckCircle2 className="size-4 text-accent" />
              <span>{isTa ? "1. கணினி வழி தானியங்கி கணிப்பு (Automated Calculations)" : "1. Automated Computer Calculations"}</span>
            </h3>
            <p className="mt-2 text-muted">
              {isTa
                ? "இத்தளத்தில் வழங்கப்படும் ஜாதகக் கட்டங்கள், நவாம்சம், பாவகம், தசா-புக்தி, அஷ்டகவர்க்கம் மற்றும் தசவிதப் பொருத்தங்கள் ஆகியவை நவீன மற்றும் பாரம்பரிய வானியல் சூத்திரங்களின்படி கணினி அல்காரிதம் மூலம் தானாகக் கணக்கிடப்படுபவை ஆகும். மனித தலையீடின்றி கணக்கிடப்படுவதால், உள்ளிடப்படும் தேதி, நேரம் மற்றும் ஊர் ஆயத்தொலைவுகளின் துல்லியத்தைப் பொறுத்தே கணிப்புகள் அமையும்."
                : "All birth charts, Navamsa, Bhava chalit, Dasa-Bhukti timelines, Ashtakavarga, and matrimonial matching results are computed automatically via mathematical algorithms based on standard astrological canons (Thirukanitham / Vakya). No manual intervention is involved; results strictly depend upon the accuracy of user inputs."}
            </p>
          </div>

          {/* Section 2 */}
          <div className="rounded-xl border border-border/70 bg-elevated/30 p-5">
            <h3 className="font-semibold text-ink text-base flex items-center gap-2">
              <CheckCircle2 className="size-4 text-accent" />
              <span>{isTa ? "2. தொழில்முறை ஆலோசனைக்கு மாற்று அல்ல (Not Professional Advice)" : "2. No Professional Advice or Guarantee"}</span>
            </h3>
            <p className="mt-2 text-muted">
              {isTa
                ? "இங்கு தரப்படும் கணிப்புகளோ, பலன்களோ அல்லது பொருத்த முடிவுகளோ சட்டப்பூர்வ, மருத்துவ, நிதி, அல்லது இறுதித் திருமண உறுதிப்பாடாகக் கருதப்படக் கூடாது. திருமணப் பொருத்தம் பார்ப்பவர்கள் வரன்-மணமகள் இருவீட்டாரும் பாரம்பரிய குடும்ப ஜோதிடரிடமும் நேரில் கலந்து ஆலோசித்து முடிவெடுக்க வேண்டும்."
                : "The astrological predictions, compatibility scores, and suggestions are strictly educational and recreational in nature. They do not constitute legal, medical, psychological, financial, or definitive matrimonial counseling. Users are strongly advised to independently verify all horoscopes with experienced traditional family astrologers."}
            </p>
          </div>

          {/* Section 3 */}
          <div className="rounded-xl border border-border/70 bg-elevated/30 p-5">
            <h3 className="font-semibold text-ink text-base flex items-center gap-2">
              <CheckCircle2 className="size-4 text-accent" />
              <span>{isTa ? "3. பொறுப்பு வரம்பு (Limitation of Liability)" : "3. Complete Limitation of Legal Liability"}</span>
            </h3>
            <p className="mt-2 text-muted">
              {isTa
                ? "இணையதளம், அச்சிடப்படும் PDF அறிக்கைகள் அல்லது திருமண சுயவிவரப் படிவத்தில் (Biodata) உள்ள தகவல்களைப் பயன்படுத்தி எடுக்கப்படும் எந்தவொரு நடவடிக்கை, இழப்பு, விவாதம் அல்லது சேதத்திற்கும் astro.codepackr.com நிர்வாகமோ, மென்பொருள் வடிவமைப்பாளர்களோ எவ்விதத்திலும் பொறுப்பேற்க மாட்டார்கள்."
                : "Under no circumstances shall astro.codepackr.com, Codepackr Technologies, its developers, or affiliates be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use this software or printable PDF reports."}
            </p>
          </div>

          {/* Section 4 */}
          <div className="rounded-xl border border-border/70 bg-elevated/30 p-5">
            <h3 className="font-semibold text-ink text-base flex items-center gap-2">
              <FileText className="size-4 text-accent" />
              <span>{isTa ? "4. PDF மற்றும் அச்சு அறிக்கைகளுக்கான விதிமுறை" : "4. Terms for Printable PDF Reports"}</span>
            </h3>
            <p className="mt-2 text-muted">
              {isTa
                ? "அச்சிடப்படும் அனைத்து PDF பக்கங்களிலும் (4 பக்க ஜாதகம், திருமணப் பொருத்தம், மற்றும் வரன் பயோடேட்டா) இந்த இணையதளப் பொறுப்புத் துறப்பானது முழுமையாகப் பொருந்தும். அறிக்கைகளில் குறிப்பிடப்பட்டுள்ள 'astro.codepackr.com/disclaimer' பக்கத்தை வாசித்து முழுமையாக ஏற்றுக் கொண்டதாகவே கருதப்படும்."
                : "All printable PDF reports generated by this application incorporate this disclaimer by reference. Users, recipients, and matrimonial parties receiving printed copies are deemed to have reviewed and agreed to these terms."}
            </p>
          </div>
        </div>

        {/* Footer info */}
        <footer className="mt-8 border-t border-border/80 pt-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted">
          <div>
            <p className="font-semibold text-fg">Codepackr Astro &bull; astro.codepackr.com</p>
            <p>Contact: codepackr@gmail.com</p>
          </div>
          <button
            type="button"
            onClick={() => go("jathagam")}
            className="rounded-lg bg-accent px-4 py-2 font-semibold text-accent-fg hover:opacity-90 transition-opacity"
          >
            {isTa ? "ஜாதகம் கணிக்க" : "Go to Jathagam"}
          </button>
        </footer>
      </article>
    </main>
  );
}
