// Codepackr Astro - Baby Name Finder Engine by Nakshatra & Pada
// Section 1D of docs/codepackr-astro-tamil-astrology-roadmap.md

export type BabyGender = "boy" | "girl" | "unisex";
export type NameCategory = "pure_tamil" | "traditional" | "modern";

export interface BabyNameItem {
  id: string;
  nameTa: string;
  transliteration: string;
  gender: BabyGender;
  meaningTa: string;
  meaningEn: string;
  startingSyllable: string;
  nakshatraIdx: number;
  pada?: number; // 1-4 or undefined if for all padas of star
  category: NameCategory;
  source: string;
}

export const BABY_NAMES_DATABASE: BabyNameItem[] = [
  // 0. அசுவினி (Chu, Che, Cho, La)
  {
    id: "ash-1",
    nameTa: "சுதன்",
    transliteration: "Sudhan",
    gender: "boy",
    meaningTa: "புத்திசாலி, நற்குணமுடைய மகன்",
    meaningEn: "Wise, virtuous son",
    startingSyllable: "சு",
    nakshatraIdx: 0,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "ash-2",
    nameTa: "சுதர்சன்",
    transliteration: "Sudarshan",
    gender: "boy",
    meaningTa: "அழகான பார்வை, விஷ்ணுவின் சக்ராயுதம்",
    meaningEn: "Pleasing vision, Vishnu's sacred disc",
    startingSyllable: "சு",
    nakshatraIdx: 0,
    pada: 1,
    category: "traditional",
    source: "வைணவ மரபு",
  },
  {
    id: "ash-3",
    nameTa: "சுபா",
    transliteration: "Subha",
    gender: "girl",
    meaningTa: "மங்களம், சுபகரமானவள்",
    meaningEn: "Auspicious, radiant",
    startingSyllable: "சு",
    nakshatraIdx: 0,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "ash-4",
    nameTa: "சுபிக்ஷா",
    transliteration: "Subiksha",
    gender: "girl",
    meaningTa: "வளமும் செழிப்பும் நிறைந்தவள்",
    meaningEn: "Prosperous and bountiful",
    startingSyllable: "சு",
    nakshatraIdx: 0,
    pada: 1,
    category: "modern",
    source: "நவீன நற்பெயர்",
  },
  {
    id: "ash-5",
    nameTa: "சேரன்",
    transliteration: "Cheran",
    gender: "boy",
    meaningTa: "பண்டைய தமிழ் சேர நாட்டு மன்னன்",
    meaningEn: "Chera king, royal Tamil heritage",
    startingSyllable: "சே",
    nakshatraIdx: 0,
    pada: 2,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "ash-6",
    nameTa: "சேதுபதி",
    transliteration: "Sethupathi",
    gender: "boy",
    meaningTa: "பாதுகாவலன், வீரம் நிறைந்த தலைவர்",
    meaningEn: "Guardian, heroic leader",
    startingSyllable: "சே",
    nakshatraIdx: 0,
    pada: 2,
    category: "traditional",
    source: "தமிழ் மரபு",
  },
  {
    id: "ash-7",
    nameTa: "சேந்தன்",
    transliteration: "Senthan",
    gender: "boy",
    meaningTa: "முருகப்பெருமான், செம்மையானவன்",
    meaningEn: "Lord Murugan, pure and radiant",
    startingSyllable: "சே",
    nakshatraIdx: 0,
    pada: 2,
    category: "pure_tamil",
    source: "பண்டைத் தமிழ்",
  },
  {
    id: "ash-8",
    nameTa: "சோழன்",
    transliteration: "Cholan",
    gender: "boy",
    meaningTa: "புகழ்பெற்ற சோழ பேரரசின் மன்னன்",
    meaningEn: "Chola king, valor and righteous rule",
    startingSyllable: "சோ",
    nakshatraIdx: 0,
    pada: 3,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "ash-9",
    nameTa: "சோபனா",
    transliteration: "Shobana",
    gender: "girl",
    meaningTa: "பிரகாசமானவள், பேரழகு மிக்கவள்",
    meaningEn: "Luminous, exceptionally beautiful",
    startingSyllable: "சோ",
    nakshatraIdx: 0,
    pada: 3,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "ash-10",
    nameTa: "லாவண்யா",
    transliteration: "Lavanya",
    gender: "girl",
    meaningTa: "இயற்கை அழகு, கருணை மற்றும் நளினம்",
    meaningEn: "Grace, elegance and beauty",
    startingSyllable: "லா",
    nakshatraIdx: 0,
    pada: 4,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },

  // 1. பரணி (Li, Lu, Le, Lo)
  {
    id: "bar-1",
    nameTa: "லித்திக்",
    transliteration: "Lithik",
    gender: "boy",
    meaningTa: "அன்பும் அறிவும் நிறைந்தவன்",
    meaningEn: "Loving and intellectually bright",
    startingSyllable: "லீ",
    nakshatraIdx: 1,
    pada: 1,
    category: "modern",
    source: "நவீன நற்பெயர்",
  },
  {
    id: "bar-2",
    nameTa: "லீலா",
    transliteration: "Leela",
    gender: "girl",
    meaningTa: "இறைவனின் திருவிளையாடல், அழகு",
    meaningEn: "Divine play, grace",
    startingSyllable: "லீ",
    nakshatraIdx: 1,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "bar-3",
    nameTa: "லோகேஷ்",
    transliteration: "Lokesh",
    gender: "boy",
    meaningTa: "உலகைக் காக்கும் இறைவன்",
    meaningEn: "Ruler / Protector of the universe",
    startingSyllable: "லோ",
    nakshatraIdx: 1,
    pada: 4,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "bar-4",
    nameTa: "லோகமித்ரா",
    transliteration: "Lokamitra",
    gender: "girl",
    meaningTa: "அனைவருக்கும் இனிய தோழி",
    meaningEn: "Friend of all the world",
    startingSyllable: "லோ",
    nakshatraIdx: 1,
    pada: 4,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },

  // 2. கார்த்திகை (A, I, U, E)
  {
    id: "kri-1",
    nameTa: "அன்பரசன்",
    transliteration: "Anbarasan",
    gender: "boy",
    meaningTa: "அன்பின் அரசன், கருணை தலைவன்",
    meaningEn: "King of love, benevolent ruler",
    startingSyllable: "அ",
    nakshatraIdx: 2,
    pada: 1,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "kri-2",
    nameTa: "அகிலன்",
    transliteration: "Akhilan",
    gender: "boy",
    meaningTa: "உலகறிந்த வீரன், முழுமையானவன்",
    meaningEn: "Conqueror of the world, complete",
    startingSyllable: "அ",
    nakshatraIdx: 2,
    pada: 1,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "kri-3",
    nameTa: "அமுதவாணன்",
    transliteration: "Amuthavanan",
    gender: "boy",
    meaningTa: "அமுதம் போன்ற இனிய குணமுடையவன்",
    meaningEn: "Sweet-natured as nectar",
    startingSyllable: "அ",
    nakshatraIdx: 2,
    pada: 1,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "kri-4",
    nameTa: "அகிலா",
    transliteration: "Akhila",
    gender: "girl",
    meaningTa: "உலக நாயகி, அகிலாண்டேஸ்வரி",
    meaningEn: "Ruler of the universe, goddess",
    startingSyllable: "அ",
    nakshatraIdx: 2,
    pada: 1,
    category: "traditional",
    source: "ஆன்மீகப் பெயர்",
  },
  {
    id: "kri-5",
    nameTa: "அனிதா",
    transliteration: "Anitha",
    gender: "girl",
    meaningTa: "அன்புமிக்கவள், கருணையுள்ளவள்",
    meaningEn: "Graceful, full of love",
    startingSyllable: "அ",
    nakshatraIdx: 2,
    pada: 1,
    category: "modern",
    source: "நவீன நற்பெயர்",
  },
  {
    id: "kri-6",
    nameTa: "இளவரசன்",
    transliteration: "Ilavarasan",
    gender: "boy",
    meaningTa: "இளைய மன்னன், எதிர்காலத் தலைவர்",
    meaningEn: "Prince, valiant young king",
    startingSyllable: "ஈ",
    nakshatraIdx: 2,
    pada: 2,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "kri-7",
    nameTa: "இனியவள்",
    transliteration: "Iniyaval",
    gender: "girl",
    meaningTa: "இனிமையான குணம் கொண்ட பெண்",
    meaningEn: "Sweet, charming and gentle lady",
    startingSyllable: "ஈ",
    nakshatraIdx: 2,
    pada: 2,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "kri-8",
    nameTa: "உதயன்",
    transliteration: "Udhayan",
    gender: "boy",
    meaningTa: "எழுச்சி கொள்பவன், சூரியோதயம் போன்றவன்",
    meaningEn: "Rising sun, flourishing leader",
    startingSyllable: "ஊ",
    nakshatraIdx: 2,
    pada: 3,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "kri-9",
    nameTa: "எழிலன்",
    transliteration: "Ezhilan",
    gender: "boy",
    meaningTa: "பேரழகு மிக்கவன்",
    meaningEn: "Handsome, radiant",
    startingSyllable: "ஏ",
    nakshatraIdx: 2,
    pada: 4,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "kri-10",
    nameTa: "எழிலரசி",
    transliteration: "Ezhilarasi",
    gender: "girl",
    meaningTa: "அழகின் அரசி",
    meaningEn: "Queen of beauty",
    startingSyllable: "ஏ",
    nakshatraIdx: 2,
    pada: 4,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },

  // 3. ரோகிணி (O, Va, Vi, Vu)
  {
    id: "roh-1",
    nameTa: "ஓவியன்",
    transliteration: "Oviyan",
    gender: "boy",
    meaningTa: "கலைஞன், சித்திரம் வரைபவன்",
    meaningEn: "Artist, painter of life",
    startingSyllable: "ஓ",
    nakshatraIdx: 3,
    pada: 1,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "roh-2",
    nameTa: "ஓவியா",
    transliteration: "Oviya",
    gender: "girl",
    meaningTa: "சித்திரம் போன்ற பேரழகி",
    meaningEn: "Painting, beautiful piece of art",
    startingSyllable: "ஓ",
    nakshatraIdx: 3,
    pada: 1,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "roh-3",
    nameTa: "வாசுகி",
    transliteration: "Vasuki",
    gender: "girl",
    meaningTa: "மங்களமானவள், திருக்குறள் திருவள்ளுவர் மனைவி",
    meaningEn: "Virtuous, sacred companion of Valluvar",
    startingSyllable: "வா",
    nakshatraIdx: 3,
    pada: 2,
    category: "pure_tamil",
    source: "தமிழ் இலக்கியம்",
  },
  {
    id: "roh-4",
    nameTa: "விஜயன்",
    transliteration: "Vijayan",
    gender: "boy",
    meaningTa: "வெற்றிவீரன், எப்போதும் வெல்பவன்",
    meaningEn: "Victorious warrior",
    startingSyllable: "வி",
    nakshatraIdx: 3,
    pada: 3,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "roh-5",
    nameTa: "வித்யாரூபன்",
    transliteration: "Vidyaroopan",
    gender: "boy",
    meaningTa: "கல்வியின் உருவமானவன்",
    meaningEn: "Embodiment of wisdom",
    startingSyllable: "வி",
    nakshatraIdx: 3,
    pada: 3,
    category: "traditional",
    source: "கல்விப் பெயர்",
  },

  // 4. மிருகசீரிடம் (Ve, Vo, Ka, Ki)
  {
    id: "mri-1",
    nameTa: "வேலன்",
    transliteration: "Velan",
    gender: "boy",
    meaningTa: "வீரவேல் தாங்கிய முருகக்கடவுள்",
    meaningEn: "Lord Murugan carrying the divine spear",
    startingSyllable: "வே",
    nakshatraIdx: 4,
    pada: 1,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "mri-2",
    nameTa: "வேந்தன்",
    transliteration: "Venthan",
    gender: "boy",
    meaningTa: "மன்னன், ஆட்சி நாயகன்",
    meaningEn: "Emperor, sovereign king",
    startingSyllable: "வே",
    nakshatraIdx: 4,
    pada: 1,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "mri-3",
    nameTa: "கார்த்திக்",
    transliteration: "Karthik",
    gender: "boy",
    meaningTa: "முருகப்பெருமான், பிரகாசமானவன்",
    meaningEn: "Lord Murugan, courageous & bright",
    startingSyllable: "கா",
    nakshatraIdx: 4,
    pada: 3,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "mri-4",
    nameTa: "காவ்யா",
    transliteration: "Kavya",
    gender: "girl",
    meaningTa: "கவிதை நயம் மிக்கவள்",
    meaningEn: "Poetic grace, literature",
    startingSyllable: "கா",
    nakshatraIdx: 4,
    pada: 3,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },

  // 5. திருவாதிரை (Ku, Gha, Nga, Chha)
  {
    id: "ard-1",
    nameTa: "குமரன்",
    transliteration: "Kumaran",
    gender: "boy",
    meaningTa: "என்றும் இளமையான தமிழ்க்கடவுள் முருகன்",
    meaningEn: "Ever youthful Lord Murugan",
    startingSyllable: "கு",
    nakshatraIdx: 5,
    pada: 1,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "ard-2",
    nameTa: "குணாளன்",
    transliteration: "Gunalan",
    gender: "boy",
    meaningTa: "நற்குணங்களின் இருப்பிடம்",
    meaningEn: "Abode of virtues",
    startingSyllable: "கு",
    nakshatraIdx: 5,
    pada: 1,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "ard-3",
    nameTa: "குமுதவல்லி",
    transliteration: "Kumudhavalli",
    gender: "girl",
    meaningTa: "செவ்வல்லி மலர் போன்ற பேரழகி",
    meaningEn: "Graceful like a water lily",
    startingSyllable: "கு",
    nakshatraIdx: 5,
    pada: 1,
    category: "pure_tamil",
    source: "தமிழ் இலக்கியம்",
  },

  // 6. புனர்பூசம் (Ke, Ko, Ha, Hi)
  {
    id: "pun-1",
    nameTa: "கேசவன்",
    transliteration: "Kesavan",
    gender: "boy",
    meaningTa: "மகாவிஷ்ணு, அழகிய திருமுடி உடையவன்",
    meaningEn: "Lord Vishnu, supreme deity",
    startingSyllable: "கே",
    nakshatraIdx: 6,
    pada: 1,
    category: "traditional",
    source: "வைணவ மரபு",
  },
  {
    id: "pun-2",
    nameTa: "கோபாலன்",
    transliteration: "Gopalan",
    gender: "boy",
    meaningTa: "உயிர்களைக் காக்கும் கிருஷ்ண பகவான்",
    meaningEn: "Lord Krishna, protector of souls",
    startingSyllable: "கோ",
    nakshatraIdx: 6,
    pada: 2,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "pun-3",
    nameTa: "ஹரினி",
    transliteration: "Harini",
    gender: "girl",
    meaningTa: "மான் போன்ற நளினம் கொண்டவள்",
    meaningEn: "Graceful like a deer",
    startingSyllable: "ஹா",
    nakshatraIdx: 6,
    pada: 3,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },

  // 7. பூசம் (Hu, He, Ho, Da)
  {
    id: "pus-1",
    nameTa: "ஹேமந்த்",
    transliteration: "Hemanth",
    gender: "boy",
    meaningTa: "பொன் போன்றவன், பனிக்காலம்",
    meaningEn: "Golden, pure heart",
    startingSyllable: "ஹே",
    nakshatraIdx: 7,
    pada: 2,
    category: "modern",
    source: "நவீன நற்பெயர்",
  },
  {
    id: "pus-2",
    nameTa: "ஹேமாவதி",
    transliteration: "Hemavathi",
    gender: "girl",
    meaningTa: "பார்வதி தேவி, தங்க நிறத்தவள்",
    meaningEn: "Goddess Parvathi, golden radiance",
    startingSyllable: "ஹே",
    nakshatraIdx: 7,
    pada: 2,
    category: "traditional",
    source: "ஆன்மீகப் பெயர்",
  },

  // 8. ஆயில்யம் (Di, Du, De, Do)
  {
    id: "ashl-1",
    nameTa: "தீபக்",
    transliteration: "Deepak",
    gender: "boy",
    meaningTa: "ஒளி விளக்கு, பிரகாசமான அறிவாளி",
    meaningEn: "Lamp, beacon of light",
    startingSyllable: "டீ",
    nakshatraIdx: 8,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "ashl-2",
    nameTa: "தீபிகா",
    transliteration: "Deepika",
    gender: "girl",
    meaningTa: "ஒளிச்சுடர், இருளை நீக்கும் பேரொளி",
    meaningEn: "Ray of light, radiant",
    startingSyllable: "டீ",
    nakshatraIdx: 8,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },

  // 9. மகம் (Ma, Mi, Mu, Me)
  {
    id: "mag-1",
    nameTa: "மாறன்",
    transliteration: "Maran",
    gender: "boy",
    meaningTa: "பண்டைய பாண்டிய மன்னன், வீரன்",
    meaningEn: "Pandian king, valiant warrior",
    startingSyllable: "மா",
    nakshatraIdx: 9,
    pada: 1,
    category: "pure_tamil",
    source: "சங்கத் தமிழ்",
  },
  {
    id: "mag-2",
    nameTa: "மாதவன்",
    transliteration: "Madhavan",
    gender: "boy",
    meaningTa: "மகாலட்சுமியின் நாயகன், விஷ்ணு",
    meaningEn: "Lord of Lakshmi, Vishnu",
    startingSyllable: "மா",
    nakshatraIdx: 9,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "mag-3",
    nameTa: "மாலினி",
    transliteration: "Malini",
    gender: "girl",
    meaningTa: "மலர் மாலை சூடியவள், நறுமணம் வீசுபவள்",
    meaningEn: "Fragrant, adorned with flowers",
    startingSyllable: "மா",
    nakshatraIdx: 9,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "mag-4",
    nameTa: "முகிலன்",
    transliteration: "Mughilan",
    gender: "boy",
    meaningTa: "மழை மேகம், கருணை பொழிபவன்",
    meaningEn: "Rain cloud, bearer of blessings",
    startingSyllable: "மூ",
    nakshatraIdx: 9,
    pada: 3,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "mag-5",
    nameTa: "மேனகா",
    transliteration: "Menaka",
    gender: "girl",
    meaningTa: "தேவலோக அழகி, கலைச்செல்வி",
    meaningEn: "Celestial beauty, graceful",
    startingSyllable: "மே",
    nakshatraIdx: 9,
    pada: 4,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },

  // 14. சுவாதி (Ru, Re, Ro, Taa)
  {
    id: "swa-1",
    nameTa: "ரூபன்",
    transliteration: "Roopan",
    gender: "boy",
    meaningTa: "அழகான தோற்றமுடையவன்",
    meaningEn: "Handsome, attractive form",
    startingSyllable: "ரூ",
    nakshatraIdx: 14,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "swa-2",
    nameTa: "ரேவந்த்",
    transliteration: "Revanth",
    gender: "boy",
    meaningTa: "சூரிய பகவானின் மகன், குதிரை வீரன்",
    meaningEn: "Son of Sun god, skilled horseman",
    startingSyllable: "ரே",
    nakshatraIdx: 14,
    pada: 2,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "swa-3",
    nameTa: "ரோஹித்",
    transliteration: "Rohit",
    gender: "boy",
    meaningTa: "சூரியனின் முதல் ஒளிக்கதிர்",
    meaningEn: "First ray of the sun",
    startingSyllable: "ரோ",
    nakshatraIdx: 14,
    pada: 3,
    category: "modern",
    source: "நவீன நற்பெயர்",
  },
  {
    id: "swa-4",
    nameTa: "தாமரை",
    transliteration: "Thamarai",
    gender: "girl",
    meaningTa: "செந்தாமரை மலர், லட்சுமி வாசம் செய்யும் மலர்",
    meaningEn: "Sacred lotus, abode of Goddess Lakshmi",
    startingSyllable: "தா",
    nakshatraIdx: 14,
    pada: 4,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },

  // 21. திருவோணம் (Ju, Je, Jo, Gha)
  {
    id: "shr-1",
    nameTa: "கண்ணன்",
    transliteration: "Kannan",
    gender: "boy",
    meaningTa: "திருமால், அனைவரையும் கவரும் இறைவன்",
    meaningEn: "Lord Krishna, beloved divine hero",
    startingSyllable: "கா",
    nakshatraIdx: 21,
    pada: 4,
    category: "pure_tamil",
    source: "தமிழ் இலக்கியம்",
  },
  {
    id: "shr-2",
    nameTa: "ஜோதி",
    transliteration: "Jothi",
    gender: "unisex",
    meaningTa: "அருட்பெருஞ்ஜோதி, ஞானச்சுடர்",
    meaningEn: "Divine luminous flame, spiritual wisdom",
    startingSyllable: "ஜோ",
    nakshatraIdx: 21,
    pada: 3,
    category: "pure_tamil",
    source: "ஆன்மீகப் பெயர்",
  },

  // 26. ரேவதி (De, Do, Cha, Chi)
  {
    id: "rev-1",
    nameTa: "தேவா",
    transliteration: "Deva",
    gender: "boy",
    meaningTa: "இறைத்தன்மை கொண்டவன், தலைவர்",
    meaningEn: "Divine leader, noble soul",
    startingSyllable: "தே",
    nakshatraIdx: 26,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "rev-2",
    nameTa: "தேவகி",
    transliteration: "Devaki",
    gender: "girl",
    meaningTa: "கண்ணனின் தாய், புண்ணியவதி",
    meaningEn: "Mother of Lord Krishna, blessed",
    startingSyllable: "தே",
    nakshatraIdx: 26,
    pada: 1,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
  {
    id: "rev-3",
    nameTa: "சாரதி",
    transliteration: "Sarathi",
    gender: "boy",
    meaningTa: "வாழ்க்கை ரதத்தை வழிநடத்தும் வழிகாட்டி",
    meaningEn: "Charioteer, wise life guide",
    startingSyllable: "சா",
    nakshatraIdx: 26,
    pada: 3,
    category: "pure_tamil",
    source: "தூய தமிழ்",
  },
  {
    id: "rev-4",
    nameTa: "சித்ரா",
    transliteration: "Chithra",
    gender: "girl",
    meaningTa: "சித்திரப் பேரழகி, ஒளிவீசுபவள்",
    meaningEn: "Bright painting, radiant star",
    startingSyllable: "சீ",
    nakshatraIdx: 26,
    pada: 4,
    category: "traditional",
    source: "பாரம்பரிய நற்பெயர்",
  },
];

export function queryBabyNames(filters: {
  nakshatraIdx?: number;
  pada?: number;
  gender?: BabyGender | "all";
  category?: NameCategory | "all";
  searchTerm?: string;
  syllable?: string;
}): BabyNameItem[] {
  return BABY_NAMES_DATABASE.filter((item) => {
    if (filters.nakshatraIdx !== undefined && item.nakshatraIdx !== filters.nakshatraIdx) {
      return false;
    }
    if (filters.pada !== undefined && item.pada !== undefined && item.pada !== filters.pada) {
      return false;
    }
    if (filters.gender && filters.gender !== "all" && item.gender !== filters.gender && item.gender !== "unisex") {
      return false;
    }
    if (filters.category && filters.category !== "all" && item.category !== filters.category) {
      return false;
    }
    if (filters.syllable && item.startingSyllable !== filters.syllable) {
      return false;
    }
    if (filters.searchTerm) {
      const q = filters.searchTerm.trim().toLowerCase();
      const matchTa = item.nameTa.toLowerCase().includes(q);
      const matchEn = item.transliteration.toLowerCase().includes(q);
      const matchMeanTa = item.meaningTa.toLowerCase().includes(q);
      const matchMeanEn = item.meaningEn.toLowerCase().includes(q);
      if (!matchTa && !matchEn && !matchMeanTa && !matchMeanEn) return false;
    }
    return true;
  });
}
