// Codepackr Astro - Nakshatra & Pada Comprehensive Astro Engine
// Section 1C of docs/codepackr-astro-tamil-astrology-roadmap.md
import {
  nakshatra,
  signIndex,
  norm360,
  dmsText,
  julianDay,
  siderealGrahas,
} from "./engine";
import {
  SIGNS_TA,
  SIGNS_EN,
  NAK_TA,
  NAK_EN,
  NAK_LORD,
  PLANET_BY_ID,
  type PlanetId,
  type School,
} from "./constants";

export interface NakshatraPadaDetail {
  nakIdx: number;
  nakTa: string;
  nakEn: string;
  pada: number;
  rasiIdx: number;
  rasiTa: string;
  rasiEn: string;
  lordId: PlanetId;
  lordTa: string;
  lordEn: string;
  deityTa: string;
  deityEn: string;
  ganaTa: string;
  ganaEn: string;
  yoniTa: string;
  yoniEn: string;
  yoniAnimalTa: string;
  yoniAnimalEn: string;
  nadiTa: string;
  nadiEn: string;
  vrikshamTa: string;
  vrikshamEn: string;
  birdTa: string;
  birdEn: string;
  elementTa: string;
  elementEn: string;
  syllableTa: string;
  syllableEn: string;
  allPadaSyllablesTa: [string, string, string, string];
  allPadaSyllablesEn: [string, string, string, string];
  characteristicsTa: string;
  characteristicsEn: string;
  favorableDirectionsTa: string;
  favorableDirectionsEn: string;
}

export const NAKSHATRA_DATA: Array<{
  idx: number;
  ta: string;
  en: string;
  lord: PlanetId;
  deityTa: string;
  deityEn: string;
  ganaTa: string;
  ganaEn: string;
  yoniTa: string;
  yoniEn: string;
  yoniAnimalTa: string;
  yoniAnimalEn: string;
  nadiTa: string;
  nadiEn: string;
  vrikshamTa: string;
  vrikshamEn: string;
  birdTa: string;
  birdEn: string;
  elementTa: string;
  elementEn: string;
  padasTa: [string, string, string, string];
  padasEn: [string, string, string, string];
  rasiDistribution: [number, number, number, number]; // sign indices for padas 1, 2, 3, 4
  charTa: string;
  charEn: string;
}> = [
  {
    idx: 0,
    ta: "அசுவினி",
    en: "Ashwini",
    lord: "ketu",
    deityTa: "அசுவினி குமாரர்கள்",
    deityEn: "Ashwini Kumaras (Divine Healers)",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "குதிரை (ஆண்)",
    yoniEn: "Horse (Male)",
    yoniAnimalTa: "குதிரை",
    yoniAnimalEn: "Horse",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "எட்டி மரம்",
    vrikshamEn: "Strychnine Tree",
    birdTa: "புள்ளிருக்கு (ராசாளி)",
    birdEn: "Hawk / Wild Falcon",
    elementTa: "நிலம் (பூமி)",
    elementEn: "Earth",
    padasTa: ["சு", "சே", "சோ", "லா"],
    padasEn: ["Chu", "Che", "Cho", "La"],
    rasiDistribution: [0, 0, 0, 0], // Aries
    charTa: "சுறுசுறுப்பு, வேகமான முடிவுகள், பிறருக்கு உதவும் குணம் மற்றும் தலைமைப் பண்பு.",
    charEn: "Energetic, agile decision maker, pioneering spirit and helpful mindset.",
  },
  {
    idx: 1,
    ta: "பரணி",
    en: "Bharani",
    lord: "venus",
    deityTa: "எம தர்மன்",
    deityEn: "Yama Dharmaraja",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "யானை (ஆண்)",
    yoniEn: "Elephant (Male)",
    yoniAnimalTa: "யானை",
    yoniAnimalEn: "Elephant",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "நெல்லி மரம்",
    vrikshamEn: "Amla (Gooseberry)",
    birdTa: "காகம்",
    birdEn: "Crow",
    elementTa: "நிலம்",
    elementEn: "Earth",
    padasTa: ["லீ", "லூ", "லே", "லோ"],
    padasEn: ["Li", "Lu", "Le", "Lo"],
    rasiDistribution: [0, 0, 0, 0], // Aries
    charTa: "உறுதியான மனவலிமை, நேர்மை, கலை ஆர்வம், தடைகளைத் தகர்த்து வெல்லும் ஆற்றல்.",
    charEn: "Courageous, determined, creative flair and capable of bearing immense responsibility.",
  },
  {
    idx: 2,
    ta: "கார்த்திகை",
    en: "Krittika",
    lord: "sun",
    deityTa: "அக்னி பகவான்",
    deityEn: "Agni Deva (Fire God)",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "ஆடு (பெண்)",
    yoniEn: "Sheep / Goat (Female)",
    yoniAnimalTa: "ஆடு",
    yoniAnimalEn: "Sheep / Goat",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "அத்தி மரம்",
    vrikshamEn: "Cluster Fig",
    birdTa: "மயில்",
    birdEn: "Peacock",
    elementTa: "நெருப்பு",
    elementEn: "Fire",
    padasTa: ["அ", "ஈ", "ஊ", "ஏ"],
    padasEn: ["A", "I", "U", "E"],
    rasiDistribution: [0, 1, 1, 1], // 1 in Aries, 2,3,4 in Taurus
    charTa: "நேர்மை, சுயமரியாதை, தலைமை தாங்கும் குணம், இலக்குகளில் அசைக்க முடியாத உறுதி.",
    charEn: "Sharp intellect, proud demeanor, high self-respect and dynamic leadership.",
  },
  {
    idx: 3,
    ta: "ரோகிணி",
    en: "Rohini",
    lord: "moon",
    deityTa: "பிரம்ம தேவன்",
    deityEn: "Brahma Deva",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "பாம்பு (ஆண்)",
    yoniEn: "Serpent (Male)",
    yoniAnimalTa: "நாகம்",
    yoniAnimalEn: "Serpent",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "நாவல் மரம்",
    vrikshamEn: "Black Plum (Jamun)",
    birdTa: "ஆந்தை",
    birdEn: "Owl",
    elementTa: "நிலம்",
    elementEn: "Earth",
    padasTa: ["ஓ", "வா", "வி", "வு"],
    padasEn: ["O", "Va", "Vi", "Vu"],
    rasiDistribution: [1, 1, 1, 1], // Taurus
    charTa: "கவர்ச்சிகரமான தோற்றம், இனிமையான பேச்சு, கலை & வணிகத் திறமை, செல்வாக்கு.",
    charEn: "Charming demeanor, artistic appreciation, eloquence and prosperity.",
  },
  {
    idx: 4,
    ta: "மிருகசீரிடம்",
    en: "Mrigashirsha",
    lord: "mars",
    deityTa: "சந்திர பகவான்",
    deityEn: "Soma / Moon God",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "சாரைப்பாம்பு (பெண்)",
    yoniEn: "Serpent (Female)",
    yoniAnimalTa: "மான் / பாம்பு",
    yoniAnimalEn: "Deer / Serpent",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "கருங்காலி மரம்",
    vrikshamEn: "Ebony Tree",
    birdTa: "கோழி",
    birdEn: "Hen / Wild Cock",
    elementTa: "நிலம்",
    elementEn: "Earth",
    padasTa: ["வே", "வோ", "கா", "கீ"],
    padasEn: ["Ve", "Vo", "Ka", "Ki"],
    rasiDistribution: [1, 1, 2, 2], // 1,2 in Taurus, 3,4 in Gemini
    charTa: "ஆராய்ச்சி மனப்பான்மை, தேடல், சுறுசுறுப்பு, பல்துறை அறிவு மற்றும் இரக்க குணம்.",
    charEn: "Curious researcher, multifaceted knowledge, active seeker and warm heart.",
  },
  {
    idx: 5,
    ta: "திருவாதிரை",
    en: "Ardra",
    lord: "rahu",
    deityTa: "ருத்ர தேவன் (சிவபெருமான்)",
    deityEn: "Rudra (Lord Shiva)",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "நாய் (பெண்)",
    yoniEn: "Dog (Female)",
    yoniAnimalTa: "நாய்",
    yoniAnimalEn: "Dog",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "செங்காலி மரம்",
    vrikshamEn: "Red Cedar / Sandal",
    birdTa: "செம்பருந்து",
    birdEn: "Kite / Eagle",
    elementTa: "நீர்",
    elementEn: "Water",
    padasTa: ["கு", "க", "ங", "ச"],
    padasEn: ["Ku", "Gha", "Nga", "Chha"],
    rasiDistribution: [2, 2, 2, 2], // Gemini
    charTa: "ஆழ்ந்த சிந்தனை, துன்பங்களைத் தாங்கி புத்துயிர் பெறும் ஆற்றல், கூர்மையான புத்தி.",
    charEn: "Deep analytical mind, resilience through trials, transformative vision.",
  },
  {
    idx: 6,
    ta: "புனர்பூசம்",
    en: "Punarvasu",
    lord: "jupiter",
    deityTa: "அதிதி (தேவர்களின் தாய்)",
    deityEn: "Aditi (Mother of Gods)",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "பூனை (பெண்)",
    yoniEn: "Cat (Female)",
    yoniAnimalTa: "பூனை",
    yoniAnimalEn: "Cat",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "மூங்கில் மரம்",
    vrikshamEn: "Bamboo",
    birdTa: "அன்னப்பறவை",
    birdEn: "Swan",
    elementTa: "காற்று",
    elementEn: "Air",
    padasTa: ["கே", "கோ", "ஹா", "ஹீ"],
    padasEn: ["Ke", "Ko", "Ha", "Hi"],
    rasiDistribution: [2, 2, 2, 3], // 1,2,3 in Gemini, 4 in Cancer
    charTa: "தர்மசிந்தனை, அமைதியான சுபாவம், கனிவான பேச்சு, மீண்டும் மீண்டும் எழுந்து நிற்கும் குணம்.",
    charEn: "Virtuous, generous, peaceful disposition, capacity for renewal and success.",
  },
  {
    idx: 7,
    ta: "பூசம்",
    en: "Pushya",
    lord: "saturn",
    deityTa: "பிரகஸ்பதி (குரு)",
    deityEn: "Brihaspati (Deva Guru)",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "ஆடு (ஆண்)",
    yoniEn: "Goat (Male)",
    yoniAnimalTa: "ஆடு",
    yoniAnimalEn: "Goat",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "அரச மரம்",
    vrikshamEn: "Peepal / Sacred Fig",
    birdTa: "நீர்க்காகம்",
    birdEn: "Cormorant / Sea Crow",
    elementTa: "நீர்",
    elementEn: "Water",
    padasTa: ["ஹூ", "ஹே", "ஹோ", "டா"],
    padasEn: ["Hu", "He", "Ho", "Da"],
    rasiDistribution: [3, 3, 3, 3], // Cancer
    charTa: "அனைத்து நட்சத்திரங்களிலும் மங்களகரமானது; அறிவு, போதனை, பக்தி மற்றும் சமுதாய மேன்மை.",
    charEn: "Highly auspicious, nourishing, spiritual wisdom, reliable mentor & counselor.",
  },
  {
    idx: 8,
    ta: "ஆயில்யம்",
    en: "Ashlesha",
    lord: "mercury",
    deityTa: "ஆதிசேஷன் (நாகராஜன்)",
    deityEn: "Adishesha / Serpent Deities",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "பூனை (ஆண்)",
    yoniEn: "Cat (Male)",
    yoniAnimalTa: "பூனை",
    yoniAnimalEn: "Cat",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "புன்னை மரம்",
    vrikshamEn: "Alexandrian Laurel",
    birdTa: "செம்போத்து",
    birdEn: "Crow Pheasant",
    elementTa: "நீர்",
    elementEn: "Water",
    padasTa: ["டீ", "டூ", "டே", "டோ"],
    padasEn: ["Di", "Du", "De", "Do"],
    rasiDistribution: [3, 3, 3, 3], // Cancer
    charTa: "அதிக நுண்ணறிவு, தந்திரோபாயம், உளவியல் அறிவாற்றல், எதையும் எளிதில் கிரகிக்கும் திறன்.",
    charEn: "Shrewd intellect, intuitive perception, mystical insights, strategic thinking.",
  },
  {
    idx: 9,
    ta: "மகம்",
    en: "Magha",
    lord: "ketu",
    deityTa: "பித்ருக்கள் (முன்னோர்கள்)",
    deityEn: "Pitrus (Ancestors)",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "எலி (ஆண்)",
    yoniEn: "Rat (Male)",
    yoniAnimalTa: "எலி",
    yoniAnimalEn: "Rat",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "ஆல மரம்",
    vrikshamEn: "Banyan Tree",
    birdTa: "ஆண் மயில்",
    birdEn: "Peacock",
    elementTa: "நீர்",
    elementEn: "Water",
    padasTa: ["மா", "மீ", "மூ", "மே"],
    padasEn: ["Ma", "Mi", "Mu", "Me"],
    rasiDistribution: [4, 4, 4, 4], // Leo
    charTa: "ராஜ யோக குணம், பரம்பரை பெருமை, தலைமை ஆளுமை, தான தர்மம் மற்றும் சுயமரியாதை.",
    charEn: "Regal presence, royal authority, ancestral pride, philanthropy and respect.",
  },
  {
    idx: 10,
    ta: "பூரம்",
    en: "Purva Phalguni",
    lord: "venus",
    deityTa: "பக தேவன்",
    deityEn: "Bhaga Deva",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "எலி (பெண்)",
    yoniEn: "Rat (Female)",
    yoniAnimalTa: "எலி",
    yoniAnimalEn: "Rat",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "பலாசு (புரசு)",
    vrikshamEn: "Flame of the Forest",
    birdTa: "பெண் மயில்",
    birdEn: "Peahen",
    elementTa: "நிலம்",
    elementEn: "Earth",
    padasTa: ["மோ", "டா", "டீ", "டூ"],
    padasEn: ["Mo", "Ta", "Ti", "Tu"],
    rasiDistribution: [4, 4, 4, 4], // Leo
    charTa: "கலை ஆர்வம், அன்பு, தாராள மனப்பான்மை, மகிழ்ச்சியான வாழ்க்கை, சிறந்த நட்பு வட்டம்.",
    charEn: "Social charm, creative zest, love for arts, hospitable nature and popularity.",
  },
  {
    idx: 11,
    ta: "உத்திரம்",
    en: "Uttara Phalguni",
    lord: "sun",
    deityTa: "ஆர்யமா தேவன்",
    deityEn: "Aryaman (Solar Deity)",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "பசு (ஆண்)",
    yoniEn: "Cow (Bull)",
    yoniAnimalTa: "பசு",
    yoniAnimalEn: "Cow",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "அலரி / இத்தி",
    vrikshamEn: "Oleander / Itthi",
    birdTa: "வண்டான்காக்கை",
    birdEn: "Beetle / Crow",
    elementTa: "நெருப்பு",
    elementEn: "Fire",
    padasTa: ["டே", "டோ", "பா", "பீ"],
    padasEn: ["Te", "To", "Pa", "Pi"],
    rasiDistribution: [4, 5, 5, 5], // 1 in Leo, 2,3,4 in Virgo
    charTa: "உதவும் குணம், நேர்மை, நட்பு, தலைமைப் பொறுப்பு, சமூகத்தில் உயர்ந்த மரியாதை.",
    charEn: "Dignified, compassionate, dependable friend, high integrity and respect.",
  },
  {
    idx: 12,
    ta: "ஹஸ்தம்",
    en: "Hasta",
    lord: "moon",
    deityTa: "சூரிய நாராயணன்",
    deityEn: "Savitr (Sun Deity)",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "எருமை (பெண்)",
    yoniEn: "Buffalo (Female)",
    yoniAnimalTa: "எருமை",
    yoniAnimalEn: "Buffalo",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "அத்தி மரம்",
    vrikshamEn: "Wild Fig",
    birdTa: "பருந்து",
    birdEn: "Vulture / Hawk",
    elementTa: "காற்று",
    elementEn: "Air",
    padasTa: ["பூ", "ஷ", "ண", "ட"],
    padasEn: ["Pu", "Sha", "Na", "Tha"],
    rasiDistribution: [5, 5, 5, 5], // Virgo
    charTa: "கைத்தொழில் மற்றும் கைவினைத்திறன், சாமர்த்தியமான பேச்சு, நகைச்சுவை, புத்திசாலித்தனம்.",
    charEn: "Dexterous hands, master craftsman, witty speech, clever and industrious.",
  },
  {
    idx: 13,
    ta: "சித்திரை",
    en: "Chitra",
    lord: "mars",
    deityTa: "விஸ்வகர்மா (தேவ சிற்பி)",
    deityEn: "Tvashtar / Vishwakarma",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "புலி (பெண்)",
    yoniEn: "Tiger (Female)",
    yoniAnimalTa: "புலி",
    yoniAnimalEn: "Tiger",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "வில்வ மரம்",
    vrikshamEn: "Bael (Sacred Bilva)",
    birdTa: "மரங்கொத்தி",
    birdEn: "Woodpecker",
    elementTa: "நெருப்பு",
    elementEn: "Fire",
    padasTa: ["பே", "போ", "ரா", "ரீ"],
    padasEn: ["Pe", "Po", "Ra", "Ri"],
    rasiDistribution: [5, 5, 6, 6], // 1,2 in Virgo, 3,4 in Libra
    charTa: "மின்னும் அழகு, வடிவமைக்கும் திறன், சுறுசுறுப்பு, கம்பீரமான தோற்றம்.",
    charEn: "Brilliant creativity, aesthetic architectural vision, eye for design.",
  },
  {
    idx: 14,
    ta: "சுவாதி",
    en: "Swati",
    lord: "rahu",
    deityTa: "வாயு பகவான் (காற்று)",
    deityEn: "Vayu Deva (Wind God)",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "எருமை (ஆண்)",
    yoniEn: "Buffalo (Male)",
    yoniAnimalTa: "எருமை",
    yoniAnimalEn: "Buffalo",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "மருத மரம்",
    vrikshamEn: "Arjuna Tree",
    birdTa: "தேனீ",
    birdEn: "Bee / Plover",
    elementTa: "காற்று",
    elementEn: "Air",
    padasTa: ["ரூ", "ரே", "ரோ", "தா"],
    padasEn: ["Ru", "Re", "Ro", "Taa"],
    rasiDistribution: [6, 6, 6, 6], // Libra
    charTa: "சுதந்திர சிந்தனை, வணிக மேன்மை, இனிமையான சுபாவம், நெகிழ்வுத்தன்மை, நீதி.",
    charEn: "Independent spirit, business acumen, adaptability and diplomatic tact.",
  },
  {
    idx: 15,
    ta: "விசாகம்",
    en: "Vishakha",
    lord: "jupiter",
    deityTa: "இந்திராக்னி (இந்திரன் & அக்னி)",
    deityEn: "Indra & Agni",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "புலி (ஆண்)",
    yoniEn: "Tiger (Male)",
    yoniAnimalTa: "புலி",
    yoniAnimalEn: "Tiger",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "விளா மரம்",
    vrikshamEn: "Wood Apple",
    birdTa: "செங்காகம்",
    birdEn: "Red Crow",
    elementTa: "நெருப்பு",
    elementEn: "Fire",
    padasTa: ["தீ", "தூ", "தே", "தோ"],
    padasEn: ["Ti", "Tu", "Te", "To"],
    rasiDistribution: [6, 6, 6, 7], // 1,2,3 in Libra, 4 in Scorpio
    charTa: "இலக்கை அடையும் வைராக்கியம், பேச்சாற்றல், தலைமைப் பண்பு, வெற்றியின் சின்னம்.",
    charEn: "Single-pointed ambition, persuasive speech, perseverance to triumph.",
  },
  {
    idx: 16,
    ta: "அனுஷம்",
    en: "Anuradha",
    lord: "saturn",
    deityTa: "மித்ர தேவன் (சூரியனின் நட்பு அம்சம்)",
    deityEn: "Mitra (Friendship & Harmony)",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "மான் (பெண்)",
    yoniEn: "Deer (Female)",
    yoniAnimalTa: "மான்",
    yoniAnimalEn: "Deer",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "மகிழ மரம்",
    vrikshamEn: "Bullet Wood",
    birdTa: "வானம்பாடி",
    birdEn: "Nightingale / Skylark",
    elementTa: "நிலம்",
    elementEn: "Earth",
    padasTa: ["நா", "நீ", "நூ", "நே"],
    padasEn: ["Na", "Ni", "Nu", "Ne"],
    rasiDistribution: [7, 7, 7, 7], // Scorpio
    charTa: "உண்மையான நட்பு, விடாமுயற்சி, அமைதியான சுபாவம், வெளிநாட்டு யோகம்.",
    charEn: "Steadfast loyalty, devoted friend, organizational skill, global fortune.",
  },
  {
    idx: 17,
    ta: "கேட்டை",
    en: "Jyeshtha",
    lord: "mercury",
    deityTa: "இந்திர தேவன்",
    deityEn: "Lord Indra",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "மான் (ஆண்)",
    yoniEn: "Deer (Male)",
    yoniAnimalTa: "மான்",
    yoniAnimalEn: "Deer",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "பராய் மரம்",
    vrikshamEn: "Streblus Asper",
    birdTa: "சக்ரவாகப் பறவை",
    birdEn: "Brahminy Duck",
    elementTa: "காற்று",
    elementEn: "Air",
    padasTa: ["நோ", "யா", "யீ", "யூ"],
    padasEn: ["No", "Ya", "Yi", "Yu"],
    rasiDistribution: [7, 7, 7, 7], // Scorpio
    charTa: "மூத்தவர் மரியாதை, பாதுகாப்பு உணர்வு, துணிச்சல், சவால்களை எதிர்கொள்ளும் தைரியம்.",
    charEn: "Senior authority, protective instinct, fearless courage in crisis.",
  },
  {
    idx: 18,
    ta: "மூலம்",
    en: "Mula",
    lord: "ketu",
    deityTa: "நிருதி (அசுர தேவதை)",
    deityEn: "Nirriti",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "நாய் (ஆண்)",
    yoniEn: "Dog (Male)",
    yoniAnimalTa: "நாய்",
    yoniAnimalEn: "Dog",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "மரா மரம் (ஆச்சாமரம்)",
    vrikshamEn: "Sal Tree",
    birdTa: "செம்பருந்து",
    birdEn: "Red Hawk",
    elementTa: "நிலம்",
    elementEn: "Earth",
    padasTa: ["யே", "யோ", "பா", "பீ"],
    padasEn: ["Ye", "Yo", "Bha", "Bhi"],
    rasiDistribution: [8, 8, 8, 8], // Sagittarius
    charTa: "வேர் வரை ஆராயும் பண்பு, சுதந்திர எண்ணம், தத்துவ நாட்டம், ஆன்மீக ஞானம்.",
    charEn: "Radical inquirer, fundamental researcher, philosophical breakthrough.",
  },
  {
    idx: 19,
    ta: "பூராடம்",
    en: "Purva Ashadha",
    lord: "venus",
    deityTa: "வருண பகவான் (நீர் தெய்வம்)",
    deityEn: "Varuna (Water Deity)",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "குரங்கு (ஆண்)",
    yoniEn: "Monkey (Male)",
    yoniAnimalTa: "குரங்கு",
    yoniAnimalEn: "Monkey",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "வஞ்சி மரம்",
    vrikshamEn: "Cane / Rattan",
    birdTa: "கோழிப்பறவை",
    birdEn: "Francolin",
    elementTa: "நீர்",
    elementEn: "Water",
    padasTa: ["பூ", "தா", "பா", "டா"],
    padasEn: ["Bhu", "Dha", "Bha", "Dha"],
    rasiDistribution: [8, 8, 8, 8], // Sagittarius
    charTa: "தோல்வியை ஏற்காத மனப்பான்மை, வாக்கு வன்மை, பிரகாசமான புன்னகை, ஆளுமை.",
    charEn: "Invincible willpower, eloquent debater, magnetic presence and pride.",
  },
  {
    idx: 20,
    ta: "உத்திராடம்",
    en: "Uttara Ashadha",
    lord: "sun",
    deityTa: "விஸ்வே தேவர்கள்",
    deityEn: "Vishvedevas (Universal Gods)",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "கீரி (ஆண்)",
    yoniEn: "Mongoose (Male)",
    yoniAnimalTa: "கீரி",
    yoniAnimalEn: "Mongoose",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "பலா மரம்",
    vrikshamEn: "Jackfruit Tree",
    birdTa: "வல்லூறு",
    birdEn: "Falcon / Eagle",
    elementTa: "நெருப்பு",
    elementEn: "Fire",
    padasTa: ["பே", "போ", "ஜா", "ஜீ"],
    padasEn: ["Bhe", "Bho", "Ja", "Ji"],
    rasiDistribution: [8, 9, 9, 9], // 1 in Sagittarius, 2,3,4 in Capricorn
    charTa: "அமைதியான வெற்றி, பொறுமை, கடமை உணர்வு, தார்மீக நெறி மற்றும் பெருந்தன்மை.",
    charEn: "Enduring success, patience, solemn responsibility and universal respect.",
  },
  {
    idx: 21,
    ta: "திருவோணம்",
    en: "Shravana",
    lord: "moon",
    deityTa: "மகாவிஷ்ணு",
    deityEn: "Maha Vishnu",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "குரங்கு (பெண்)",
    yoniEn: "Monkey (Female)",
    yoniAnimalTa: "குரங்கு",
    yoniAnimalEn: "Monkey",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "எருக்கு மரம்",
    vrikshamEn: "Calotropis / Crown Flower",
    birdTa: "நாரை",
    birdEn: "Crane / Heron",
    elementTa: "காற்று",
    elementEn: "Air",
    padasTa: ["ஜூ", "ஜே", "ஜோ", "கா"],
    padasEn: ["Ju", "Je", "Jo", "Gha"],
    rasiDistribution: [9, 9, 9, 9], // Capricorn
    charTa: "செவிமடுத்து கற்கும் திறன், கல்வி ஆர்வம், பக்தி, கீர்த்தி மற்றும் சர்வ ஜன வசியம்.",
    charEn: "Keen listener, erudite scholar, spiritual elevation, public fame.",
  },
  {
    idx: 22,
    ta: "அவிட்டம்",
    en: "Dhanishta",
    lord: "mars",
    deityTa: "அஷ்ட வசுக்கள்",
    deityEn: "Ashta Vasus (Eight Gods of Abundance)",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "சிங்கம் (பெண்)",
    yoniEn: "Lion (Female)",
    yoniAnimalTa: "சிங்கம்",
    yoniAnimalEn: "Lion",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "வன்னி மரம்",
    vrikshamEn: "Prosopis / Shami Tree",
    birdTa: "பொன்வண்டு",
    birdEn: "Golden Beetle",
    elementTa: "நிலம்",
    elementEn: "Earth",
    padasTa: ["கா", "கீ", "கூ", "கே"],
    padasEn: ["Ga", "Gi", "Gu", "Ge"],
    rasiDistribution: [9, 9, 10, 10], // 1,2 in Capricorn, 3,4 in Aquarius
    charTa: "இசை மற்றும் கலை ஆர்வம், செல்வாக்கு, தான தர்மம், தைரியம் மற்றும் கம்பீரம்.",
    charEn: "Musical rhythm, immense wealth, courage, philanthropic leadership.",
  },
  {
    idx: 23,
    ta: "சதயம்",
    en: "Shatabhisha",
    lord: "rahu",
    deityTa: "வருண பகவான் (நூறு மருத்துவர்கள்)",
    deityEn: "Varuna (Divine Physician)",
    ganaTa: "ராட்சச கணம்",
    ganaEn: "Rakshasa (Fierce)",
    yoniTa: "குதிரை (பெண்)",
    yoniEn: "Horse (Female)",
    yoniAnimalTa: "குதிரை",
    yoniAnimalEn: "Horse",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "கடம்ப மரம்",
    vrikshamEn: "Kadamba Tree",
    birdTa: "அண்டங்காக்கை",
    birdEn: "Raven",
    elementTa: "காற்று",
    elementEn: "Air",
    padasTa: ["கோ", "சா", "சீ", "சூ"],
    padasEn: ["Go", "Sa", "Si", "Su"],
    rasiDistribution: [10, 10, 10, 10], // Aquarius
    charTa: "மருத்துவத் திறன், ரகசியங்களை அறியும் ஆற்றல், சுதந்திரம், தீர்க்கதரிசனம்.",
    charEn: "Healing gift, esoteric visionary, independent philosopher, truthful.",
  },
  {
    idx: 24,
    ta: "பூரட்டாதி",
    en: "Purva Bhadrapada",
    lord: "jupiter",
    deityTa: "அஜைகபாதர் (ருத்ர அம்சம்)",
    deityEn: "Aja Ekapada (Fire Serpent)",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "சிங்கம் (ஆண்)",
    yoniEn: "Lion (Male)",
    yoniAnimalTa: "சிங்கம்",
    yoniAnimalEn: "Lion",
    nadiTa: "வாதம் (ஆதி நாடி)",
    nadiEn: "Vata (Adi Nadi)",
    vrikshamTa: "தேமா (மாமரம்)",
    vrikshamEn: "Mango Tree",
    birdTa: "உள்ளான்",
    birdEn: "Snipe / Plover",
    elementTa: "காற்று",
    elementEn: "Air",
    padasTa: ["சே", "சோ", "தா", "தீ"],
    padasEn: ["Se", "So", "Dha", "Dhi"],
    rasiDistribution: [10, 10, 10, 11], // 1,2,3 in Aquarius, 4 in Pisces
    charTa: "ஆன்மீக தியாகம், பேச்சாற்றல், தத்துவ விளக்கம், உயர்ந்த கோட்பாடுகள்.",
    charEn: "Spiritual asceticism, philosophical devotion, passionate teacher.",
  },
  {
    idx: 25,
    ta: "உத்திரட்டாதி",
    en: "Uttara Bhadrapada",
    lord: "saturn",
    deityTa: "அஹிர்புத்னியர் (ஆழ்கடல் நாகம்)",
    deityEn: "Ahirbudhnya (Cosmic Dragon)",
    ganaTa: "மானுட கணம்",
    ganaEn: "Manushya (Human)",
    yoniTa: "பசு (பெண்)",
    yoniEn: "Cow (Female)",
    yoniAnimalTa: "பசு",
    yoniAnimalEn: "Cow",
    nadiTa: "பித்தம் (மத்திய நாடி)",
    nadiEn: "Pitta (Madhya Nadi)",
    vrikshamTa: "வேப்ப மரம்",
    vrikshamEn: "Neem Tree",
    birdTa: "கொக்கு",
    birdEn: "Kite / Heron",
    elementTa: "நீர்",
    elementEn: "Water",
    padasTa: ["தூ", "ச", "ஞ", "த"],
    padasEn: ["Dhu", "Sha", "Jna", "Tha"],
    rasiDistribution: [11, 11, 11, 11], // Pisces
    charTa: "கருணை உள்ளம், அமைதி, தியான நாட்டம், பிறர் போற்றும் பெருந்தன்மை, தர்மம்.",
    charEn: "Compassionate calm, meditative wisdom, generous soul, virtuous guidance.",
  },
  {
    idx: 26,
    ta: "ரேவதி",
    en: "Revati",
    lord: "mercury",
    deityTa: "பூஷா தேவன் (பயணங்களின் பாதுகாவலர்)",
    deityEn: "Pushan (Protector of Travelers)",
    ganaTa: "தேவ கணம்",
    ganaEn: "Deva (Divine)",
    yoniTa: "யானை (பெண்)",
    yoniEn: "Elephant (Female)",
    yoniAnimalTa: "யானை",
    yoniAnimalEn: "Elephant",
    nadiTa: "சிலேத்துமம் (அந்திய நாடி)",
    nadiEn: "Kapha (Antya Nadi)",
    vrikshamTa: "இலுப்பை மரம்",
    vrikshamEn: "Mahua Tree",
    birdTa: "வல்லூறு",
    birdEn: "Eagle / Pigeon",
    elementTa: "நீர்",
    elementEn: "Water",
    padasTa: ["தே", "தோ", "சா", "சீ"],
    padasEn: ["De", "Do", "Cha", "Chi"],
    rasiDistribution: [11, 11, 11, 11], // Pisces
    charTa: "நேர்த்தியான பழக்கவழக்கம், பிரயாண ஆர்வம், பிறரை வழிநடத்தும் ஆற்றல், ஐஸ்வர்யம்.",
    charEn: "Refined manners, safe journey guide, nurturing prosperity and artistic joy.",
  },
];

export function getNakshatraDetail(nakIdx: number, pada: number = 1): NakshatraPadaDetail {
  const normNak = ((nakIdx % 27) + 27) % 27;
  const normPada = Math.min(4, Math.max(1, pada));
  const data = NAKSHATRA_DATA[normNak];
  const rasiIdx = data.rasiDistribution[normPada - 1];

  const lordMeta = PLANET_BY_ID[data.lord];

  return {
    nakIdx: normNak,
    nakTa: data.ta,
    nakEn: data.en,
    pada: normPada,
    rasiIdx,
    rasiTa: SIGNS_TA[rasiIdx],
    rasiEn: SIGNS_EN[rasiIdx],
    lordId: data.lord,
    lordTa: lordMeta.ta,
    lordEn: lordMeta.en,
    deityTa: data.deityTa,
    deityEn: data.deityEn,
    ganaTa: data.ganaTa,
    ganaEn: data.ganaEn,
    yoniTa: data.yoniTa,
    yoniEn: data.yoniEn,
    yoniAnimalTa: data.yoniAnimalTa,
    yoniAnimalEn: data.yoniAnimalEn,
    nadiTa: data.nadiTa,
    nadiEn: data.nadiEn,
    vrikshamTa: data.vrikshamTa,
    vrikshamEn: data.vrikshamEn,
    birdTa: data.birdTa,
    birdEn: data.birdEn,
    elementTa: data.elementTa,
    elementEn: data.elementEn,
    syllableTa: data.padasTa[normPada - 1],
    syllableEn: data.padasEn[normPada - 1],
    allPadaSyllablesTa: data.padasTa,
    allPadaSyllablesEn: data.padasEn,
    characteristicsTa: data.charTa,
    characteristicsEn: data.charEn,
    favorableDirectionsTa: "கிழக்கு மற்றும் வடக்கு",
    favorableDirectionsEn: "East & North",
  };
}

export function computeNakshatraFromMoon(lon: number): NakshatraPadaDetail {
  const n = nakshatra(lon);
  return getNakshatraDetail(n.idx, n.pada);
}

export function computeNakshatraFromDate(
  date: { year: number; month: number; day: number; hour: number; minute: number },
  tz: number = 5.5,
  school: School = "thirukanitham"
): NakshatraPadaDetail & { moonLon: number; dms: string } {
  const jd = julianDay(date.year, date.month, date.day, date.hour + date.minute / 60 - tz);
  const grahas = siderealGrahas(jd, school);
  const moonLon = grahas.bodies.moon;
  const detail = computeNakshatraFromMoon(moonLon);

  return {
    ...detail,
    moonLon,
    dms: dmsText(moonLon),
  };
}
